apiVersion: v1
kind: Namespace
metadata:
  labels:
    operator: operator-utils-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    operator: operator-utils-operator
spec:
  selector:
    matchLabels:
      operator: operator-utils-operator
  replicas: 1
  template:
    metadata:
      labels:
        operator: operator-utils-operator
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
