apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator-utils.example.io/v1alpha1",
          "kind": "MyCRD",
          "metadata": {
            "name": "mycrd-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: operator-utils.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: EnforcingCRD
      name: enforcingcrds.operator-utils.example.io
      version: v1alpha1
    - kind: EnforcingPatch
      name: enforcingpatches.operator-utils.example.io
      version: v1alpha1
    - description: MyCRD is the Schema for the mycrds API
      displayName: My CRD
      kind: MyCRD
      name: mycrds.operator-utils.example.io
      version: v1alpha1
    - kind: TemplatedEnforcingCRD
      name: templatedenforcingcrds.operator-utils.example.io
      version: v1alpha1
  description: operator-utils
  displayName: operator-utils
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOIAAADfCAMAAADcKv+WAAAAh1BMVEX39/cAAAD////8/PxLS0vd3d329vbx8fGDg4N7e3vNzc1eXl7o6Ojj4+PS0tLq6uq7u7uJiYlwcHCSkpJiYmLW1tbExMQeHh5qamqqqqo3NzednZ3CwsK1tbV1dXUpKSkQEBBYWFhAQECampqPj49RUVGlpaUnJycdHR0+Pj4TExMwMDBHR0cU28eiAAALUklEQVR4nO2d23bqOAyGE6uQlpYCPQA9Q4G2u/T9n29CEiAHH2RZdjJr5b+Ym9lN/OHYlmRZjqJevXr16tWrV69IpGq7DUcBiIqA57HLi4v1oH3IA11y+5W25qzPRxbGi/igF64fjKSUbvj4dPUc17Xk+Okviof9jVvqyLT3kvn2okGX6YGhUX/nx321wQhisPmT4x3E8KFWnr67CQwJYvKyV/PF8at7g+qfx1NQRjG40/HF8ZyfMI6vJ8FmHTFe6gH9EKZ6C9ORkFwaABm+UqGaxJIAHSmmJkCOcSh8PlwvGBoGIVMj1Ijxe+S1I8Xg20jIMl7Eu/oFi1uPHSnmRsB4yvT+H8077r0xiqdwhHCre8vfjZ+PVbyEI0zfdh/oReV3foUkTPtRYx2mugL2jhRvYQkjuNG/7Jn7Y4VRYELECszjkp40MRMyWG1V6VYOfkbxGZ4w1YfhnWM+RsP0dpCP9RgeDS/dsyHCoJU+TH/ajeG1M67XimZopqYXT/YGmAbIDdN7jFbNtS+Lyvj9MHXj0ETI9VtKZPxUWRCNb/FoFqf9+E//bpaFw9yJCcNbVDLNqhxfqnkkXnl1xIUhjsLhgGuDiQfdeo6n6N8+d3673nHL5JkQ9A6A+2xu+k54Qvv6JijCcYXGrs8HXYQh0719L1r6enq36tLxJzaaiXH8ZosI8GY3DxoiKo4TOph9/VdLRPG2iuOh3Z9oQ5tbt24Upth+HI/sEPPBPbX7I32UY2L1rEaDVsyIxfRlO4ATnevotjAjvH2rDoHCk99YIsJEtzy7WHGYkM2TxfPhOKjs56hEs3RcOHSjYdnNZDE7nqcNywGctUWzQjtsrwIiPIxf+uE8dw0IjRGv6omB7s6JmRlxhUUU1+c/Iq1lMNyqGkH/VM3mW4y2oMqEMbU9ExUk2WcVVwjEL9S4qhDSQ2cCpvKlmupxoHrxH+YHhDKh2xQootuNJGxF3ABAIWKmxyqha24VgBg3vti9nVF4epY5RozqkxohRzhCJPWY0pr0UHNUI5Np87th6b5wuNFiUnvsO4URXlGIhnHQdBQsrXDlg2vNI7mOYxzifqhps8QVIhg3UsGkGoMk+VU4xPhTnfMjc/acgxFHAVQ/VkI/Inbdcn0/yh8OyVryrxkjrzUDzN6xwq0ame4lOT8gpr+Sf/rBuvdZnVmX1j4MwtU4avE0rGQ4gxBzubdOm96RjGtbRHMYtayreXJIfc9y4aPbe1WulWvQrM5Y9Yf+dHOfRMgp9az93ezr6Wv7rhvENl40irHaj892+Y6G1BCauNaMM2PVnPu2Ss617kWM3EJmUsbqvPprYZNjgjfWYp1Qj4xVt+8Xn8yByNWw152XBLaaa4tmFAsPiDgf2pqxtoQjGTG5ffZizuw6NbaWbYViFHarIlILXxuSBEbhY65hX/jLDa5Z/AMTI5iT+UnyuHFuywiIVHCCnn3uKlszjo2pDARxW296RtN4hOGanXDlEzDCzzlwPCmL2EK1lJ9F0ZYRkpflVZF+yc3obcVQM0rs1SKudZH/L/HAisgUe7NhXDX68ZwfMco60nCawE7e0jptGMunFfKc/cSYeoMXvxtlz1iNvmaMiLxprEJ8pjlG1Sb/KfnI9VhNNulgjqGg5M90azJWfeTFKdYBDSc/Mw+MJyZw2oWsQFBnPPZj0oiZ/eZRXQ63kbg7RmasfqsFI0gSP3bZcGTwORYhzgFrGLPxKE8122TD0flTXYQ7sq5gTFugitNkTnriSLgPT9jsx0TlHj4fGofcTFVpF/orlTKqE+myszTGgy86XbZVzQWTOJTpYJO4zDhejsUiGZFR0mwTnWyPr9v5SC0ZDwYA1Y4LVBhDzYj7VjMHQZ++rNDMcifMByMmBaxYOOx3qWaT9ktjVTIoNcr2dZE/x1H7r6QLgLiqErGiG/cvc0XSXfwxu+U/eU8TkjBPrK114x0IABGNNutqzsL+/WkMrRY2K6uef6TWoGHGHfOxUkyY3E6/Ntvt/cvbfJCwFbrjkIWzm20KlhM4qhlnkOUwHP7bEopCVu58NhrP6/9Dx1jkwlR3OWuXx6qKYRfUgyfLdn80OylQnBN7DuvBE2U+Bl1XFjvOfpifVs1OrOwJ48/sUz1sAXiqGsQrTA2ihoqU7pVx97ULIu4AF6mQ/wdCciiGlH7dijBnoeRat+8c4URy/XItFOnDXRMoz1chtO2akSaX02bT4rVLdrZE+d4vNvgm17qt+sgoQX7G1SksGsuT3TsiGOWbFFHiuNn0MepqRw5/i31RmLhuqF12syNzfy8zwGBiLnaq108XO7JYD1fZNhEMd46M8WXn1o/Tiv+dO0MWZ2kU+ujAHQJllWyaIs0fUVzZpFZKz6tUCREWDhFMrpWNR+q6O+5xPZZdzBViaq4UotdvV2adZrS++MRg6GbpxP7qFdpJth+xLBY2MXZN5Vt2YImU77iczlWKkaM9t289mqPcU9oWPz+IqaOx46d8qDthydQEeiQgV6sDUr8vuDzeNyISu/3Dut7b+1aNO58nx0g8GupY6rVrK66D2NtdPRVuPIB9ALmkjzZSpLC719/TY0r/o1MOMWMNaGbCVPt5DgnR2oXR500QjoSp/h3PLThlLXq/tqROaNfa4g4gy8yMmgJflmTtD+bZam5nM0K6VxSPt6g1Yiotr9UmGCMtVpol5SFqhnaBkRoN/jk4y44hD59ltt0Jj3kLsgon3WJ06YYsw9bxCKr/b5VO+Fkc+nE98eabkU44O206IUqjauV37aATlupT2SUeSeTTBqDPNJUKXGLtyOgv653ehzXH3fVTjX1FH9kIGQ71+alSwEfIcY7YByOdUDbLJ66Rcg9VUXgJOQ71cTMyEzqnPRzEmzBHJ1SuYa5pD8yMHgglp4vtxRez8kHIssvK1o9+CF0jOZyMvgjNVz2FYqQTmg/fORtyLIw+CXlK+rkyeiVkKgfnxkiPXyP9HYcUXR5GegPQHh2DBeBiy9EJLTavJ84GeUzf06ET2uywOAaPC9F85DCEPFYOjTEUIdO0SmAMMg6P73J3rAiMdELKyGdZOiwZwxKmc45zjq4tI52QHP0z3lCMEX6MtEAIzeJUPhnpdqlDBBduOEwAZOyRdMbSlZAn0BHjbpugr8SOmTE8jIhzkPQigs5xTZ76hYhWUFMqGCLwLIzGt5BDRix7RQyMe1M7yJEGpt0wd7fDWGITGivw98PVgznzmW2/z5XReMlO48T6xSi7aWVuiAYyZhm6zavXxglB1Dpxe0yY1Q9R1jxKuKHnrZoJ6yOxVFhVaI4HMe+CQUKtm24mrE+n3+W/UJckYN/LhCEtZIUgjET1TyoF45WmuZddd4pvhSGsI1aKOKtqZ/jJZyb4jyjCOmK1BJR8xfSVHQK2+Q44QgKiv9N3ljkdSMI6YuWiP+kdbT7PF1rV+McS1hEr6TKyN/o9QWnBiK9uX0OMS5WuZEaH71MFaEaL+v31u59KN+CK5pUC/ivM4gpXWt1Q0KiM/F6croeoadyEqKGLmlfR4zBTw117nh/McJg2w2OBSsyumQkjaKIslpcPkoT1UEV061crN2Rb3hB911y4sz0GRvsCjsiKuiFPLwmdLUcoUYnb2w98uFdyxQGdEJcJE+bES0kqxgfa1rA5+550l7Sb5IzUQqpGkyLgHSsnwZqR0Hg1UhuE0riKUzFc9fBur4xAI+hAG4dHaUzD9opB1MtuOzZENecs2zldXzRqxkiYPu5GEoz6bLnATql6LsvlvGI8q1qmd6PWyyWePi5jVB/7wGi0eXhOOVf76+08aR0wOu3uMpqPh6rrUZKcr4VsXYd7AXY37Y4X34Lo/1ILt1evXr169erVq1evXr16dVv/AUvfmr1C/cP4AAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - operator-utils.example.io
          resources:
          - enforcingcrds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator-utils.example.io
          resources:
          - enforcingcrds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operator-utils.example.io
          resources:
          - enforcingpatches
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator-utils.example.io
          resources:
          - enforcingpatches/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operator-utils.example.io
          resources:
          - mycrds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator-utils.example.io
          resources:
          - mycrds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operator-utils.example.io
          resources:
          - templatedenforcingcrds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator-utils.example.io
          resources:
          - templatedenforcingcrds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: operator-utils-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/raffaelespazzoli/operator-utils:latest
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - utils
  links:
  - name: Operator Utils
    url: https://operator-utils.domain
  maintainers:
  - email: raffaele.spazzoli@gmail.com'
    name: '''raffaele spazzoli'
  maturity: alpha
  provider:
    name: Red Hat Community of Practice
    url: https://github.com/redhat-cop/operator-utils
  version: 0.0.1
