apiVersion: v1
kind: Service
metadata:
  labels:
    operator: operator-utils-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: operator-utils-operator-certs    
  name: controller-manager-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    operator: operator-utils-operator
