apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: myoperator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - myoperator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - example.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - example
  resources:
  - '*'
  - enforcingcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
